services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      - "${WINDOWS_HOST_IP:-host.docker.internal}:5173"
      - "--host-header=rewrite"
    environment:
      - NGROK_AUTHTOKEN=3H9tTo9kqtVFYFPBOElBJsw9zqC_5NVYZvLaMANE75KDZpbsD
    ports:
      - "4040:4040"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wp
      POSTGRES_USER: wp_user
      POSTGRES_PASSWORD: wp_password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
